apiVersion: apps/v1
kind: Deployment
metadata:
  name: football
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: xotlr333/ktdsfootball:v3
          ports:
            - containerPort: 8080
              name: springboot-port
      imagePullSecrets:
        - name: regcred