apiVersion: v1
kind: Service
metadata:
  name: football-service
spec:
  type: LoadBalancer
  selector:
    app: football
  ports:
    - name: football
      port: 8080
      targetPort: 8080
      protocol: TCP